const makeProduct = (overrides) => ({
  category: '굿즈',
  shop: '굿즈픽 스토어',
  price: '18,000원',
  stockText: '재고 있음',
  shipping: '픽업·배송',
  accent: '#eee8ff',
  ...overrides,
});

const makeUpcomingProduct = (overrides) => makeProduct({
  status: 'UPCOMING',
  openType: 'NEW',
  alertCount: 0,
  stockText: null,
  shipping: null,
  ...overrides,
});

const demoUpcomingOpenAt = new Date(Date.now() + 42 * 60 * 1000).toISOString();

export const homeMockUserState = {
  isAuthenticated: true,
  interestCategoryIds: ['idol', 'photocard'],
};

export const homeMockData = {
  badges: { notifications: 3, cart: 2 },
  banners: [
    {
      id: 'promotion-nearby',
      type: 'PROMOTION',
      eyebrow: '가을 굿즈 기획전',
      title: '내 주변 굿즈샵 재고,\n픽업까지 한 번에',
      cta: '지금 보기',
      tone: 'purple',
      linkType: 'EVENT',
      linkValue: 'autumn-goods',
      startAt: '2026-10-01T00:00:00+09:00',
      endAt: '2026-10-31T23:59:59+09:00',
      impressionCount: 1284,
      clickCount: 96,
    },
    {
      id: 'ad-binder',
      type: 'AD',
      advertiserName: '하비박스',
      eyebrow: '하비박스 · 굿즈 보관용품',
      title: '포카 바인더\n전 품목 20% 할인',
      cta: '자세히 보기',
      tone: 'peach',
      linkType: 'SHOP',
      linkValue: 'hobby-box',
      startAt: '2026-10-05T00:00:00+09:00',
      endAt: '2026-10-20T23:59:59+09:00',
      impressionCount: 842,
      clickCount: 54,
    },
    {
      id: 'promotion-photocard',
      type: 'PROMOTION',
      eyebrow: '포토카드 위크',
      title: '최애 포토카드\n최대 20% 할인',
      cta: '둘러보기',
      tone: 'mint',
      linkType: 'CATEGORY',
      linkValue: 'photocard',
      startAt: '2026-10-08T00:00:00+09:00',
      endAt: '2026-10-25T23:59:59+09:00',
      impressionCount: 611,
      clickCount: 41,
    },
  ],
  categories: [
    { id: 'idol', name: '아이돌', icon: 'mic', isHomeShortcut: true, sortOrder: 1 },
    { id: 'animation', name: '애니메이션', icon: 'play', isHomeShortcut: true, sortOrder: 2 },
    { id: 'photocard', name: '포토카드', icon: 'card', isHomeShortcut: true, sortOrder: 3 },
    { id: 'keyring', name: '키링', icon: 'link', isHomeShortcut: true, sortOrder: 4 },
    { id: 'all', name: '전체', icon: 'grid', isHomeShortcut: true, sortOrder: 5 },
  ],
  popularProducts: [
    makeProduct({
      id: 'popular-1',
      category: '포토카드',
      shop: '모모굿즈 홍대점',
      name: '아이돌 포토카드 세트 (10장)',
      price: '18,000원',
      popularityScore: 98,
      accent: '#eae2ff',
    }),
    makeProduct({
      id: 'popular-2',
      category: '인형 키링',
      shop: '포카하우스 강남',
      name: '토끼 키링 인형',
      price: '12,000원',
      popularityScore: 91,
      stockText: '재고 3개',
      stockTone: 'danger',
      accent: '#ffe9ee',
    }),
    makeProduct({
      id: 'popular-3',
      category: '피규어',
      shop: '하비룸 대구',
      name: '미니 피규어 블라인드 박스',
      price: '16,000원',
      popularityScore: 87,
      accent: '#e3f2fa',
    }),
    makeProduct({
      id: 'popular-4',
      category: '응원봉',
      shop: '덕질상점 신촌',
      name: '공식 미니 응원봉',
      price: '14,500원',
      popularityScore: 82,
      accent: '#fff2cf',
    }),
  ],
  newProducts: [
    makeProduct({
      id: 'new-1',
      category: '키링',
      shop: '별빛상점',
      name: '별자리 아크릴 키링',
      price: '9,900원',
      releasedAt: '2026-10-09T10:00:00+09:00',
      isNew: true,
      accent: '#f1e8ff',
    }),
    makeProduct({
      id: 'new-2',
      category: '슬로건',
      shop: '포카하우스 강남',
      name: '아이돌 슬로건 타월',
      price: '15,000원',
      releasedAt: '2026-10-08T14:00:00+09:00',
      isNew: true,
      stockText: '재고 4개',
      stockTone: 'danger',
      accent: '#ffe7ee',
    }),
    makeProduct({
      id: 'new-3',
      category: '바인더',
      shop: '덕질상점 신촌',
      name: '포토카드 바인더 A5',
      price: '13,500원',
      releasedAt: '2026-10-07T11:00:00+09:00',
      isNew: true,
      accent: '#e4f3fb',
    }),
  ],
  upcomingProducts: [
    makeUpcomingProduct({
      id: 'upcoming-1',
      category: '피규어',
      shop: '굿즈스팟 건대',
      name: '별빛소녀 한정판 피규어',
      price: '39,000원',
      openAt: demoUpcomingOpenAt,
      alertCount: 1284,
      accent: '#ffe8ee',
    }),
    makeUpcomingProduct({
      id: 'upcoming-2',
      category: '포토카드',
      shop: '모모굿즈 홍대점',
      name: '아이돌 랜덤 포토카드 2탄',
      price: '5,000원',
      openAt: '2026-10-09T21:00:00+09:00',
      openType: 'RESTOCK',
      alertCount: 862,
      accent: '#ece8ff',
    }),
    makeUpcomingProduct({
      id: 'upcoming-3',
      category: '키링',
      shop: '토끼상점 성수',
      name: '토순이 인형 키링',
      price: '12,000원',
      openAt: '2026-10-10T19:00:00+09:00',
      alertCount: 645,
      accent: '#e5f4ed',
    }),
    makeUpcomingProduct({
      id: 'upcoming-4',
      category: '응원봉',
      shop: '별빛상점',
      name: '콘서트 공식 응원봉',
      price: '39,000원',
      openAt: '2026-10-11T14:00:00+09:00',
      openType: 'RESTOCK',
      alertCount: 512,
      accent: '#e4f2fa',
    }),
    makeUpcomingProduct({
      id: 'upcoming-5',
      category: '아크릴 스탠드',
      shop: '애니굿즈 합정',
      name: '주인공 아크릴 스탠드',
      price: '18,000원',
      openAt: '2026-10-12T12:00:00+09:00',
      alertCount: 488,
      accent: '#fff1d9',
    }),
    makeUpcomingProduct({
      id: 'upcoming-6',
      category: '인형',
      shop: '포카하우스 강남',
      name: '미니 캐릭터 인형',
      price: '24,000원',
      openAt: '2026-10-14T18:00:00+09:00',
      alertCount: 374,
      accent: '#f3e8ff',
    }),
    makeUpcomingProduct({
      id: 'upcoming-7',
      category: '문구',
      shop: '소담굿즈 성수',
      name: '캐릭터 다이어리 세트',
      price: '16,000원',
      openAt: '2026-10-16T10:00:00+09:00',
      alertCount: 291,
      accent: '#e7f5f2',
    }),
    makeUpcomingProduct({
      id: 'upcoming-8',
      category: '포토카드',
      shop: '모모굿즈 홍대점',
      name: '컴백 기념 포토카드 세트',
      price: '19,000원',
      openAt: '2026-10-18T15:00:00+09:00',
      alertCount: 255,
      accent: '#ffe9ef',
    }),
    makeUpcomingProduct({
      id: 'upcoming-9',
      category: '피규어',
      shop: '하비룸 대구',
      name: '미니 피규어 시크릿 에디션',
      price: '22,000원',
      openAt: '2026-10-20T20:00:00+09:00',
      openType: 'RESTOCK',
      alertCount: 198,
      accent: '#e5f0fa',
    }),
    makeUpcomingProduct({
      id: 'upcoming-10',
      category: '앨범',
      shop: '굿즈픽 공식샵',
      name: '가을 스페셜 앨범',
      price: '28,000원',
      openAt: '2026-10-22T18:00:00+09:00',
      alertCount: 176,
      accent: '#ede8ff',
    }),
  ],
  recommendationProducts: [
    makeProduct({
      id: 'recommend-1',
      category: '포토카드',
      shop: '포카하우스 강남',
      name: '컴백 포토카드 홀더 세트',
      price: '11,000원',
      popularityScore: 79,
      interestCategoryIds: ['idol', 'photocard'],
      accent: '#eee8ff',
    }),
    makeProduct({
      id: 'recommend-2',
      category: '아크릴 스탠드',
      shop: '애니굿즈 합정',
      name: '주인공 데스크 아크릴 스탠드',
      price: '18,000원',
      popularityScore: 76,
      interestCategoryIds: ['animation'],
      accent: '#e4f3fb',
    }),
    makeProduct({
      id: 'recommend-3',
      category: '키링',
      shop: '토끼상점 성수',
      name: '토순이 말랑 키링',
      price: '8,500원',
      popularityScore: 73,
      interestCategoryIds: ['animation', 'keyring'],
      accent: '#ffe9ee',
    }),
    makeProduct({
      id: 'recommend-4',
      category: '문구',
      shop: '굿즈픽 공식샵',
      name: '최애 앨범 데코 스티커 팩',
      price: '6,000원',
      popularityScore: 70,
      interestCategoryIds: ['idol'],
      accent: '#fff2cf',
    }),
    makeProduct({
      id: 'recommend-5',
      category: '인형',
      shop: '별빛상점',
      name: '별빛소녀 미니 봉제 인형',
      price: '21,000원',
      popularityScore: 68,
      interestCategoryIds: ['animation'],
      accent: '#e5f4ed',
    }),
  ],
  lowStockProducts: [
    makeProduct({
      id: 'stock-1',
      category: '포토카드',
      shop: '모모굿즈 홍대점',
      name: '한정판 포토카드 세트',
      price: '22,000원',
      stockQuantity: 1,
      stockLabel: '재고 1개 남음',
      stockText: null,
      accent: '#eee6ff',
    }),
    makeProduct({
      id: 'stock-2',
      category: '피규어',
      shop: '하비룸 대구',
      name: '미니 피규어 (시크릿)',
      price: '14,000원',
      stockQuantity: 2,
      stockLabel: '재고 2개 남음',
      stockText: null,
      accent: '#e5f3fa',
    }),
    makeProduct({
      id: 'stock-3',
      category: '키링',
      shop: '포카하우스 강남',
      name: '스티커 키링 (퍼스널)',
      price: '9,900원',
      stockQuantity: 4,
      stockLabel: '재고 4개 남음',
      stockText: null,
      accent: '#ffe8ef',
    }),
  ],
};
