export const searchMockData = {
  defaultRecentSearches: [
    '토끼 키링',
    '모모굿즈',
    '포토카드 바인더',
    '아크릴 스탠드',
    '재입고 알림',
  ],
  popularUpdatedAt: '10.09 18:00 기준',
  popularKeywords: [
    { rank: 1, keyword: '포토카드', change: 2, trend: 'up' },
    { rank: 2, keyword: '아크릴 스탠드', change: 1, trend: 'down' },
    { rank: 3, keyword: '인형 키링', trend: 'new' },
    { rank: 4, keyword: '랜덤 피규어', change: 1, trend: 'up' },
    { rank: 5, keyword: '응원봉', change: 1, trend: 'down' },
    { rank: 6, keyword: '포카 바인더', trend: 'same' },
    { rank: 7, keyword: '반짝펫', change: 3, trend: 'up' },
    { rank: 8, keyword: '부산 굿즈샵', trend: 'new' },
    { rank: 9, keyword: '스티커', change: 2, trend: 'down' },
    { rank: 10, keyword: '팝업스토어', trend: 'same' },
  ],
  regions: [
    { id: 'busan', label: '부산', displayName: '부산광역시', sido: '부산광역시', aliases: ['부산'] },
    { id: 'seomyeon', label: '서면', displayName: '부산 부산진구 (서면)', sido: '부산광역시', sigungu: '부산진구', area: '서면', aliases: ['서면'] },
    { id: 'hongdae', label: '홍대', displayName: '서울 마포구 (홍대)', sido: '서울특별시', sigungu: '마포구', area: '홍대', aliases: ['홍대'] },
    { id: 'seongsu', label: '성수', displayName: '서울 성동구 (성수)', sido: '서울특별시', sigungu: '성동구', area: '성수', aliases: ['성수'] },
  ],
  autocompleteItems: [
    { id: 'goods-rabbit-keyring', type: '굿즈', label: '토끼 키링 인형', subtitle: '토끼마을 이야기', searchTerms: ['토순이', '키링'] },
    { id: 'goods-busan-keyring', type: '굿즈', label: '부산 한정 갈매기 키링', subtitle: '토끼굿즈 서면점', searchTerms: ['부산', '서면', '키링'] },
    { id: 'goods-busan-photocard', type: '굿즈', label: '부산 팝업 포토카드 세트', subtitle: '포토엔굿즈 서면점', searchTerms: ['부산', '서면', '포토카드'] },
    { id: 'goods-binder', type: '굿즈', label: '포토카드 바인더 A5', subtitle: '덕질상점 신촌', searchTerms: ['포토', '바인더'] },
    { id: 'work-rabbit-village', type: '작품', label: '토끼마을 이야기', subtitle: '애니메이션', searchTerms: ['토순이', '토끼'] },
    { id: 'work-starlight', type: '작품', label: '별빛소녀', subtitle: '애니메이션', searchTerms: ['별빛', '피규어'] },
    { id: 'character-tosoon', type: '캐릭터', label: '토순이', subtitle: '토끼마을 이야기의 캐릭터', searchTerms: ['토끼', '키링'] },
    { id: 'character-maru', type: '캐릭터', label: '마루', subtitle: '별빛소녀의 캐릭터', searchTerms: ['별빛', '피규어'] },
    { id: 'shop-rabbit-seomyeon', type: '굿즈샵', label: '토끼샵 부산 서면점', subtitle: '부산 부산진구 · 서면', entityId: 'rabbit-seomyeon', searchTerms: ['부산', '서면', '토끼샵'] },
    { id: 'shop-photo-seomyeon', type: '굿즈샵', label: '포토엔굿즈 서면점', subtitle: '부산 부산진구 · 서면', entityId: 'photo-seomyeon', searchTerms: ['부산', '서면', '포토'] },
    { id: 'shop-rabbit-seongsu', type: '굿즈샵', label: '토끼굿즈 성수점', subtitle: '서울 성동구 · 성수', entityId: 'rabbit-seongsu', searchTerms: ['서울', '성수', '토끼'] },
    { id: 'shop-momo-hongdae', type: '굿즈샵', label: '모모굿즈 홍대점', subtitle: '서울 마포구 · 홍대', entityId: 'momo-hongdae', searchTerms: ['서울', '홍대', '포토카드'] },
  ],
  shops: [
    { id: 'rabbit-seomyeon', name: '토끼샵 부산 서면점', sido: '부산광역시', sigungu: '부산진구', area: '서면', address: '부산 부산진구 서면로 21', categories: ['키링', '인형', '문구'] },
    { id: 'photo-seomyeon', name: '포토엔굿즈 서면점', sido: '부산광역시', sigungu: '부산진구', area: '서면', address: '부산 부산진구 중앙대로 680', categories: ['포토카드', '바인더'] },
    { id: 'rabbit-seongsu', name: '토끼굿즈 성수점', sido: '서울특별시', sigungu: '성동구', area: '성수', address: '서울 성동구 연무장길 12', categories: ['키링', '인형'] },
    { id: 'momo-hongdae', name: '모모굿즈 홍대점', sido: '서울특별시', sigungu: '마포구', area: '홍대', address: '서울 마포구 와우산로 88', categories: ['포토카드', '아이돌'] },
  ],
  searchProducts: [
    { id: 'search-1', category: '키링', shop: '토끼샵 부산 서면점', shopId: 'rabbit-seomyeon', name: '토순이 말랑 키링', price: '9,000원', work: '토끼마을 이야기', character: '토순이', accent: '#ffe8ef', location: { sido: '부산광역시', sigungu: '부산진구', area: '서면' } },
    { id: 'search-2', category: '인형', shop: '토끼샵 부산 서면점', shopId: 'rabbit-seomyeon', name: '토순이 미니 인형', price: '16,000원', work: '토끼마을 이야기', character: '토순이', accent: '#e5f4ed', location: { sido: '부산광역시', sigungu: '부산진구', area: '서면' } },
    { id: 'search-3', category: '포토카드', shop: '포토엔굿즈 서면점', shopId: 'photo-seomyeon', name: '부산 팝업 포토카드 세트', price: '12,000원', work: '별빛소녀', character: '마루', accent: '#ece8ff', location: { sido: '부산광역시', sigungu: '부산진구', area: '서면' } },
    { id: 'search-4', category: '키링', shop: '토끼굿즈 성수점', shopId: 'rabbit-seongsu', name: '토끼 키링 인형', price: '11,000원', work: '토끼마을 이야기', character: '토순이', accent: '#fff0d8', location: { sido: '서울특별시', sigungu: '성동구', area: '성수' } },
    { id: 'search-5', category: '포토카드', shop: '모모굿즈 홍대점', shopId: 'momo-hongdae', name: '아이돌 포토카드 세트', price: '18,000원', work: '별빛소년단', character: '하루', accent: '#e3f2fa', location: { sido: '서울특별시', sigungu: '마포구', area: '홍대' } },
  ],
};
